### ISSUE TITLE
WebGPU Example

### ISSUE THREAD

**Issue by DjDeveloperr** [konsumer/deno-minifb#2]
How should it work? I don't think it's possible to render WebGPU frames into window using minifb without a lot of copying going on, thought the output I got is pretty impressive, still runs like 11-12 FPS though:

![img](https://cdn.discordapp.com/attachments/783319033730564098/886574035331334144/webgpu-minifb.gif)

SwapChain could be a better alternative (basically rendering directly onto raw window handle of minifb's Window), but that needs some work on Deno's side (which I could probably give a try, unlikely I'll be successful because neither I'm familiar with contributing to deno nor good with Rust). 🤔

**Comment by konsumer** [comment]
Hehe, yeh, we should probly put a big warning in example code, and maybe remove webgpu from "stuff you can do" in README. I suspected it would be possible, but run way too slow to actually make stuff with.

I wonder if there isn't another way to "get a cross-platform window we can draw to" that would be faster. How is FPS for canvas?

As a sidenote, I couldn't get the patched deno to build on osx, but I just got it on linux, so I can do a bit of testing, now.

**Comment by DjDeveloperr** [comment]
> I wonder if there isn't another way to "get a cross-platform window we can draw to" that would be faster.

In case of WebGPU, it'd be a raw-window-handle and SwapChain and it'll work perfect.

> How is FPS for canvas?

It's quite weird, ~20 fps at the beginning and ~48-50 later on after some seconds, there seems to be some background process going on with canvaskit.

**Comment by konsumer** [comment]
> In case of WebGPU, it'd be a raw-window-handle and SwapChain and it'll work perfect.

Nice. excited to see how it fits together.  I was thinking more like some GL-ish way to send the buffer directly to the texture, but I'm not sure how it would work. I think the conversion of byteformat (u8 RGBA to u32 0RGB) could be done in shader-space, if it was operating on a plane surface, as an example, which would greatly speed up 2d or 3d->2d->3d, but that is still maybe not the best way to draw 3d (direct calls to 3d would work better then rendering to 2d first, and back to 3d.)

> there seems to be some background process going on with canvaskit.

Yeh, I looked through the other issues with deno-canvas and saw [this](https://github.com/DjDeveloperr/deno-canvas/issues/5), which might be related.

Related to both things: I wonder if maybe native (non-wasm) wrapper in deno-canvas would tie the window & canvas stuff together better, like if we already need native for canvas, we could benefit from the rest of the native skia ecosystem. I know they do native GL acceleration and other stuff. [this](https://github.com/rust-skia/rust-skia) seems cool, but I think there are a few wrappers/interfaces to choose from, and we could even use the upstream C++. It seems like now we are going `wasm <-> deno <-> ffi` for all this to work, and accepting the tradeoffs of each transfer, but maybe there is a better way that just uses `deno<->ffi` that would cut down on the wasm startup-time, and make transfers faster. I dunno, maybe deno FFI just isn't there, yet, but it'd be cool to ffi-link to the original skia, with no native adapter-code (just ffi in deno-space) so the instructions are essentially "install skia, and put this import in your code."

**Comment by konsumer** [comment]
I also start thinking about stuff like [this](https://github.com/maierfelix/nvk). "Porting" canvas/webgl APIs to vulkan may be a bit too ambitious, but if we had a vulkan interface it could open up a lot of possibilities for fullspeed native 3D games in deno, even if they didn't mirror web-apis (but I think  that'd be very cool too.)

**Comment by konsumer** [comment]
we may get even more performance form something like [tao](https://docs.rs/tao/0.5.2/tao/) ([github](https://github.com/tauri-apps/tao)), rust-side. I just found it, but it seems more geared towards just doing the window, but allowing you to make a context inside it, in various ways. I could see getting a handle, then returning a few different rust-side contexts (webgl, canvas, etc) and using that more directly, with more code in rust than wasm/deno. It sounds like a huge undertaking, but would probably give us the most performance for 2D & 3D web APIs.

> Tao doesn’t directly provide any methods for drawing on a Window. However it allows you to retrieve the raw handle of the window (see the [platform](https://docs.rs/tao/0.5.2/tao/platform/index.html) module and/or the [raw_window_handle](https://docs.rs/tao/0.5.2/tao/window/struct.Window.html#method.raw_window_handle) method), which in turn allows you to create an OpenGL/Vulkan/DirectX/Metal/etc. context that can be used to render graphics.

It can do windows on Windows, macOS, Linux, iOS and Android, so it may support some future deno platforms, once they are supported.

**Comment by konsumer** [comment]
[this](https://github.com/jrmuizel/raqote-examples/blob/master/examples/minifb.rs) is a nice example of minifb + raqote (a rust implementation of canvas) which gives me all kinds of ideas around using that to make a canvas, instead of the `wasm<->deno<->ffi` situation with skia canvas.

[servo's canvas](https://github.com/servo/servo/tree/master/components/canvas) appears to use raqote to create a 2D and webgl canvas, so that might have a lot of the work already done.

Maybe I am looking at too many options.

**Comment by DjDeveloperr** [comment]
I too *think* native canvas would perform a lot better. It should be quite doable to make native Skia bindings for Deno and use that to polyfill Canvas API, as wasm compiled skia is not so nice with performance. Raqote could be used too, I have tried doing it with Raqote before but didn't get to complete it. Tao seems something like winit, not sure how we could use that instead 🤔 
Maybe, even [cairo](https://cairographics.org/) might be a good one as it's used in node-canvas, but my experience working with that on Windows (lol and probably only for Windows) was not good, it depends on gtk and all that.

Also about format conversion, I think webgpu probably provides a way to set it.

**Comment by konsumer** [comment]
> Tao seems something like winit, not sure how we could use that instead 🤔

Yep, seems like it based on it, but they add more target-platforms (and implement the 3d backends and appindicator.) It might be overkill for this, but I do like the idea of supporting OpenGL/Vulkan, and possibly ios/android in the future (when deno supports it.) I need to look into it more, but it seems cool. I am still wondering about doing webgl more directly. like 3d -> 2d -> ffi -> rust and back seems like a lot of transfers and data-munging, but I probly don't fully understand what needs to be done. Servo seems to do both 2D & WebGL, in their canvas.

> Maybe, even cairo might be a good one as it's used in node-canvas, but my experience working with that on Windows (lol and probably only for Windows) was not good, it depends on gtk and all that.

Yeh, agreed. In my limited understanding, it's a bit heavy-handed. It renders SVGs (and canvas-like things) really well, but it's kinda huge and painful to add to a non-gtk project.

> Raqote could be used too, I have tried doing it with Raqote before but didn't get to complete it.

Maybe with my help it will go easier. Was there anything in particular that was extra tricky? I am pretty new to rust, but I have a strong interest. I think the result would be much better than wasm canvaskit. I am ok with native (not wasm) Skia too, if you think it would be easier. I get the feeling that raqote is a bit nicer to work with, and has a closer-to-canvas interface to start with, but I may be off there.

With `buffer` FFI-type, I think maybe we have all that we need. In reading servo's canvas code, it looks like it has a sort of event-pipe that it sends commands down, and the canvas responds to them. I feel like we could get some inspiration from that, but am totally unsure how to do it, or if that's an appropriate approach. I do think a big trick to get more performance might be keeping the canvas->window transfers in rust, as much as possible (just send a manager commands and occasional data from deno, that act in rust space, using raqote/etc.) One thing that comes to mind is reaching back into deno from rust, liek with a callback (for things like events and such.) I think passing functions is still missing from deno FFI. Maybe it could be done by polling an FFI function to check for new events that deno needs to act on.

Another thing, too, is if we make tidy FFI bindings, I could see this being usable in node and even other languages like python. I have worked with `cbinddgen` a bit, and is helpful to generate an interface .h file (which is in turn used in other languages to generate their own ffi bindings.) In this case, though, if we had a central manager function (that sends messages on a pipe like servo does) it might not be as helpful (it's really just the one function exposed to FFI.)

I am a big fan of generating code, especially if I'm implementing an existing API. On that front, I generated JSON that represents all the canvas APIs with [this script](https://gist.github.com/konsumer/be0f9cb3b8df083c3a594a5f08824743). It's pretty basic, and I didn't grab info about method-params, but I can set it up, if you think it would be useful for code-generation. I imagine it would go like this: generate deno classes that look like each of the applicable web classes (`HTMLCanvasElement`,  `ImageData`, `CanvasRenderingContext2D `, etc) complete with `description` fields as jsdocs and stuff, and then add (auto-generated) methods that send messages over the "ffi pipe" to a raqote + minifb handler, and add `get`/`set` for properties that use pipe/polling/etc to handle that. There might be a way to auto-generate the rust-side stuff too, I'm not sure.

For a small example:

```json
{
"ImageBitmapRenderingContext": {
    "transferFromImageBitmap": {
      "name": "transferFromImageBitmap",
      "description": "Displays the given ImageBitmap in the canvas associated with this rendering context. Ownership of the ImageBitmap is transferred to the canvas. This was previously named transferImageBitmap(), but was renamed in a spec change. The old name is being kept as an alias to avoid code breakage.",
      "method": true,
      "parent": "ImageBitmapRenderingContext",
      "readOnly": false,
      "url": "https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapRenderingContext/transferFromImageBitmap"
    }
  }
}
```

would turn into something like this:

```ts
/**
 * The ImageBitmapRenderingContext interface is a canvas rendering context that provides the functionality to replace the canvas's contents with the given ImageBitmap. Its context id (the first argument to HTMLCanvasElement.getContext() or OffscreenCanvas.getContext()) is "bitmaprenderer".
 * This interface is available in both the window and the worker context.
 */
class ImageBitmapRenderingContext {
  /**
  Displays the given ImageBitmap in the canvas associated with this rendering context. Ownership of the ImageBitmap is transferred to the canvas. This was previously named transferImageBitmap(), but was renamed in a spec change. The old name is being kept as an alias to avoid code breakage.
  https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapRenderingContext/transferFromImageBitmap
  @param {ImageBitmap} bitmap An ImageBitmap object to transfer.
  */
  transferFromImageBitmap(bitmap: ImageBitmap) {
    ffi_pipe_send(['ImageBitmapRenderingContext.transferFromImageBitmap', bitmap])
  }
}
```

I just went and manually looked up the params & docs for the class, but that is what I am thinking about. I imagine `ffi_pipe_send` would create a buffer that is easy to deserialize on rust side, and pull a known-to-rust id out of `bitmap`.

An example message to serialize/deserialize would be like this:

```json
{
  "call": "ImageBitmapRenderingContext.transferFromImageBitmap",
  "args": [ INSTANCE_ID_OF_BITMAP ]
}
```

I dunno if any of this makes sense, just thinking through it. In many cases it would probly need pointers for `this`, canvas, context, etc, so it will be shaped a bit different. Sometimes I use code-generation to get the "first pass", then edit things by hand to make them work better.

**Comment by DjDeveloperr** [comment]
Raqote probably is good enough for canvas (though its still slower than Skia). I was going to do a `canvas-2d` crate (using Raqote and some parts from Servo's implementation) in Rust and use that, but never got enough time to complete that. Raqote can provide you with a `&[u8]` slice directly using `get_data` (and it's in exact format we need!) and we can probably write a FFI function that gets pointer to that u8 slice and we could use it with `deno-minifb`. 
Honestly, IPC seems a bit overkill for our case to me.

I thought about skia being a better option because it's fast and used in Chrome for complete canvas stuff and probably more.

**Comment by konsumer** [comment]
> Raqote probably is good enough for canvas (though its still slower than Skia).
> I thought about skia being a better option because it's fast and used in Chrome for comple
> Honestly, IPC seems a bit overkill for our case to me.

You have worked with this space a lot more, so I completely trust your judgement. The render-target list for skia seems pretty extensive. I also looked at [skia-canvas](https://github.com/samizdatco/skia-canvas) for node, and it might have some good ideas, even though it is also offline-only.

**Comment by DjDeveloperr** [comment]
Doing native `canvas` through `rust-skia` seems like a pretty good idea to me, or we could even just fork `skia-canvas` and port to use Deno FFI instead of NAPI 🤔 

Aside, I don't have a lot time these days because of school and exams, so probably won't have much time to put into dev until October.

**Comment by konsumer** [comment]
> or we could even just fork skia-canvas and port to use Deno FFI instead of NAPI thinking

I really like this idea. The binding code looks really simple, and I'm not sure what it would take to replicate in deno-ffi. It might just be helpful for pointing out what actually needs to be wrapped (even if wrapping it will be a lot more involved.) It seems like it is also not a live canvas, but would at least improve render performance, and give us more direct access. Looks like it uses [neon](https://neon-bindings.com/) to interface with node. Maybe the neon peeps are interested in deno-support. That could open up  a lot of native node-lib possibilities.

Would `canvas.toBuffer()` be fast enough to work well with the other ideas we have been talking about (using a raw handle from a window library)?

**Comment by DjDeveloperr** [comment]
I think neon is too much tied to Node.js that adding Deno support would either be too hard or almost impossible (and likely out of scope for them, NAPI exposes a lot more functionality than Deno would add for security/safety reasons...), porting would probably be best option (maintaining could be easy too, perhaps skia-canvas could accept a PR for feature-gated FFI support to make a Deno build). `toBuffer` returns encoded Image so that's not what we need. I'm pretty sure Skia should be able to provide us with raw ARGB data.

**Comment by konsumer** [comment]
> I think neon is too much tied to Node.js that adding Deno support would either be too hard or almost impossible (and likely out of scope for them, NAPI exposes a lot more functionality than Deno would add for security/safety reasons...),

I mostly agree, but neon-contributor [showed interest in possibly exploring it](https://github.com/neon-bindings/neon/issues/790) in the future. I think it could open up lots of other FFI-based neon-wrapper kinds of things (for other languages, too) even if the scope of the neon-ffi wrapper is severely limited.

> porting would probably be best option (maintaining could be easy too, perhaps skia-canvas could accept a PR for feature-gated FFI support to make a Deno build).

It definitely makes sense to choose a path that doesn't wait for neon-ffi, and then move that direction later, if it's a nicer interface. I like the idea of working with skia-canvas team. It might make all 3 projects nicer, and more useful (deno-canvas, deno-minifb, and skia-canvas.) I'm unsure of what exactly would be needed. What do you think?

**Comment by konsumer** [comment]
Aside: can you take a look at that example I checked in. I was trying to figure out how you originally made screenshot above, but it is broken (my loop is wrong.)

```
Overload 1 of 3, '(arrayLike: Iterable<number>, mapfn?: ((v: number, k: number) => number) | undefined, thisArg?: any): Uint8Array', gave the following error.
    Argument of type 'GPUBuffer' is not assignable to parameter of type 'Iterable<number>'.
      Property '[Symbol.iterator]' is missing in type 'GPUBuffer' but required in type 'Iterable<number>'.  Overload 2 of 3, '(arrayLike: ArrayLike<number>): Uint8Array', gave the following error.
    Argument of type 'GPUBuffer' is not assignable to parameter of type 'ArrayLike<number>'.
      Property 'length' is missing in type 'GPUBuffer' but required in type 'ArrayLike<number>'.
      win.updateWithBuffer(Uint8Array.from(outputBuffer));
                                           ~~~~~~~~~~~~
    at file:///Users/konsumer/Documents/otherdev/deno-minifb/examples/webgpu.ts:50:44

    '[Symbol.iterator]' is declared here.
        [Symbol.iterator](): Iterator<T>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at asset:///lib.es2015.iterable.d.ts:51:5    'length' is declared here.
        readonly length: number;
                 ~~~~~~
        at asset:///lib.es5.d.ts:1464:14
make: *** [webgpu] Error 1
```

**Comment by DjDeveloperr** [comment]
You'll have to map the buffer with flag MAP_READ and getMappedRange() then construct Uint8Array from that ArrayBuffer (and then unmap it)

**Comment by DjDeveloperr** [comment]
> I mostly agree, but neon-contributor showed interest in possibly exploring it in the future. I think it could open up lots of other FFI-based neon-wrapper kinds of things (for other languages, too) even if the scope of the neon-ffi wrapper is severely limited.

That's amazing! I wish they are able to add support for Deno, it would open up lot of possibilities.

> It definitely makes sense to choose a path that doesn't wait for neon-ffi, and then move that direction later, if it's a nicer interface. I like the idea of working with skia-canvas team. It might make all 3 projects nicer, and more useful (deno-canvas, deno-minifb, and skia-canvas.) I'm unsure of what exactly would be needed. What do you think?

I suppose it would be just a single file or so that exposes the canvas-related FFI (I took a quick look at source earlier, it's pretty neat and should be easy to use for FFI), and feature-gated through `deno-ffi` feature.

**Comment by konsumer** [comment]
I struggled with this a bit, but couldn't figure out a way to do it, that worked. If you are interested in playing with the demo in [example](https://github.com/konsumer/deno-minifb/blob/main/examples/webgpu.ts) it might go better for you. I think the current code (marked with a [TODO](https://github.com/konsumer/deno-minifb/blob/3cc1f249323e7c41ef2d3868d4d806734de47ca5/examples/webgpu.ts#L46)) is where the issue is, but I'm not totally sure.

**Comment by konsumer** [comment]
> That's amazing! I wish they are able to add support for Deno, it would open up lot of possibilities.

I know, right!? This is very exciting. If I were better with rust, I could prioritize working on at least a thin neon-like wrapper, and move it forward, but I fear I am not good enough to do this, in any practical way, right now.

> I suppose it would be just a single file or so that exposes the canvas-related FFI (I took a quick look at source earlier, it's pretty neat and should be easy to use for FFI), and feature-gated through deno-ffi feature.

yep, agreed. I feel like there are a few levels of zoom to finding a workable solution:

- make a neon-like adapter that uses FFI (even if it's kinda lame, and doesn't do any of the cool stuff it can do with NAPI) and compile it linked to that instead
- port the wrapper to use plain FFI directly (not neon)
- port the wrapper, up a level in deps, directly to the underlying rust render lib

I think all 3 are doable by a competent rust programmer, but that just isn't me, yet.

**Comment by DjDeveloperr** [comment]
I can do the second, but I've not got enough time to give it right now, as I've got exams. But once I'm done with them (4th October), I'll give this a shot!

**Comment by konsumer** [comment]
A sort of sidenote: I have been trying to think about how to do more of this in wasm-space, to get around needing FFI extension. I read [this article](https://medium.com/wasmer/wasmer-io-devices-announcement-6f2a6fe23081) whcih shows how they use the WASI framebuffer to do graphics, within wasm. Not sure how far along the deno WASM interface would take us with this, but I really like the idea (no native deps, faster than ffi, compile once, etc.)

**Comment by DjDeveloperr** [comment]
Hmm, that seems something wasmer specific that gives standalone WASM binaries access to window & framebuffer, Not sure how'll that work with Deno.

**Comment by konsumer** [comment]
it's [WASI](https://wasi.dev/) (a standard wasm system interface) with a few wasmer-specific things. I am imagining the eventual wasm goals that deno has will be similar to those wasmer-specific things, but maybe I am misunderstanding the planned direction for deno wasm.

**Comment by samizdatco** [comment]
> Doing native `canvas` through `rust-skia` seems like a pretty good idea to me, or we could even just fork `skia-canvas` and port to use Deno FFI instead of NAPI 🤔

Believe it or not, I've been giving some thought to what a deno FFI api for skia-canvas would look like as well. The main issue I'm unclear on is how to tie the lifetimes of the various rust structs that hold state to the javascript 'proxy' objects that user code interacts with. Does deno have a mechanism for triggering rust deallocations based on js objects being garbage collected?

On the rendering-to-a-window front, you might take a look at my [gl fork](https://github.com/samizdatco/skia-canvas/tree/gl) and the [`Window` ](https://github.com/samizdatco/skia-canvas/blob/gl/lib/index.js#L641) class whose *display()* method opens a window and kicks off an event loop. Note that the fork is from last summer and is a couple releases behind the official release, but should be pretty easy to sync back up.

**Comment by DjDeveloperr** [comment]
Deno FFI doesn't really have any such mechanism, it just provides you with pretty low level libffi bindings. Your best bet is to use Thread Local Storage to make some sort of "resources" and operate on them using FFI calls. For example, make a thread local `RefCell<HashMap<u32, RustObject>>` then use it like `name.with(|rc| { ... })`. You will have to manually clear up memory as well. Also, for making rust deallocs based on JS objects being garbage collected you can hook a callback for when an object is GC'd using [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry).

**Comment by konsumer** [comment]
@samizdatco I hadn't had a chance to checkout skia-canvas and the gl/gpu-render branches. This looks cool! I can't get gl to build (looks like it needs python2 and some other stuff.) Is gpu-render also for opening a visual window? I can get that branch to build, but it doesn't look like it has `Window`. How do I use it?

```
{
  Canvas: [class Canvas extends RustClass] {
    parent: WeakMap { <items unknown> },
    contexts: WeakMap { <items unknown> }
  },
  CanvasGradient: [class CanvasGradient extends RustClass],
  CanvasPattern: [class CanvasPattern extends RustClass],
  CanvasRenderingContext2D: [class CanvasRenderingContext2D extends RustClass],
  CanvasTexture: [class CanvasTexture extends RustClass],
  TextMetrics: [class TextMetrics],
  Image: [class Image extends RustClass],
  ImageData: [class ImageData],
  Path2D: [class Path2D extends RustClass],
  loadImage: [Function: loadImage],
  DOMPoint: [class DOMPoint],
  DOMMatrix: [class DOMMatrix],
  DOMRect: [class DOMRect],
  FontLibrary: FontLibrary {}
}
```
